# Generated by Django 4.1 on 2023-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("customer", models.CharField(max_length=50)),
                ("quality", models.CharField(max_length=50)),
                ("wrapCt", models.IntegerField()),
                ("wrapRate_GST", models.IntegerField()),
                ("wrap_GST", models.IntegerField()),
                ("weftCt", models.IntegerField()),
                ("weftRate_GST", models.IntegerField()),
                ("weft_GST", models.IntegerField()),
                ("weave", models.CharField(max_length=100)),
                ("width_in", models.IntegerField()),
                ("epi", models.IntegerField()),
                ("ppi", models.IntegerField()),
                ("insertion", models.IntegerField()),
                ("reedSpace", models.IntegerField()),
                ("shrinkage", models.IntegerField()),
                ("wastage", models.IntegerField()),
                ("pickRate", models.IntegerField()),
                ("sizing", models.IntegerField()),
                ("transportation", models.IntegerField()),
                ("pkgRate", models.IntegerField()),
                ("rejectPercent", models.IntegerField()),
                ("interestPercent", models.IntegerField()),
                ("commissionPercent", models.IntegerField()),
                ("marginPercent", models.IntegerField()),
                ("orderQty_mtrs", models.IntegerField()),
            ],
        ),
    ]
